# -*- coding: utf-8 -*-
"""IR - CA2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkXBwyXMJ9kVdQjOOlykaLR0DgWA2cIE

## **Page Rank**

### **Power Iterative Method**
"""

import numpy as np

def powerIteration(adjMat, maxIters = 100):
    n = adjMat.shape[0]
    # pageRanks = np.ones(n) / n
    pageRanks = np.array([[0],
                         [1],
                         [0],
                         [0]])

    for i in range(maxIters):
        newRanks = adjMat.dot(pageRanks)

        if np.allclose(pageRanks, newRanks):
            print("Convergence in step:", i)
            break

        pageRanks = newRanks
    return pageRanks

adjMat = np.array([[0, 1/3, 1/3, 1/3],
                  [1, 0, 1/3, 1/3],
                  [0, 1/3, 0, 1/3],
                  [0, 1/3, 1/3, 0]])
print(powerIteration(adjMat))

"""### **Eigen Values Method**"""

import numpy as np
import numpy.linalg as la

def eigenRank(adjMat):
    eVals, eVecs = la.eig(adjMat)
    order = np.absolute(eVals).argsort()[::-1]
    eVals = eVals[order]
    eVecs = eVecs[:, order]
    pageRanks = eVecs[:, 0]
    return np.real(pageRanks / np.sum(pageRanks))

adjMat = np.array([[0, 1/3, 1/3, 1/3],
                  [1, 0, 1/3, 1/3],
                  [0, 1/3, 0, 1/3],
                  [0, 1/3, 1/3, 0]])
print(eigenRank(adjMat))

"""## **Hyperlink Induced Topic Search**"""

import numpy as np
import numpy.linalg as la

def hits(adjMat):
    mat1 = adjMat.dot(adjMat.T)
    mat2 = adjMat.T.dot(adjMat)
    eVals1, eVecs1 = la.eig(mat1)
    eVals2, eVecs2 = la.eig(mat2)
    order1 = np.absolute(eVals1).argsort()[::-1]
    order2 = np.absolute(eVals2).argsort()[::-1]
    eVals1 = eVals1[order1]
    eVals2 = eVals2[order2]
    eVecs1 = eVecs1[:, order1]
    eVecs2 = eVecs2[:, order2]
    hubs = eVecs1[:, 0]
    auths = eVecs2[:, 0]

    return np.real(hubs / np.sum(hubs)), np.real(auths / np.sum(auths))

adjMat = np.array([[0, 1/3, 1/3, 1/3],
                  [1, 0, 1/3, 1/3],
                  [0, 1/3, 0, 1/3],
                  [0, 1/3, 1/3, 0]])
hubs, auths = hits(adjMat)
print("Hub Scores:", hubs)
print("Authority Scores:", auths)